Sprint #10. Add friends, likes and top popular movies
kruglikovv/java-filmorate pull request #3
Opened 2023-04-06 23:47 UTC by kruglikovv

2023-04-07 15:35 UTC, ohelly requested changes
Привет! В целом отличная работа, прекрасный код. Есть несколько замечаний, которые необходимо исправить, чтобы я смог принять работу. Также я оставил ряд рекомендаций, на которые стоит обратить внимание.
В случае вознкновения вопросов можно обращаться ко мне в пачку

2023-04-07 15:35 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService) {
Рекомендация: Чтобы не писать конструктор вручную, можно использовать аннотацию ломбока ``@RequiredArgsConstructor``, которая создаст автоматически конструктор для всех final полей и они заинжектятся.
![image](https://user-images.githubusercontent.com/51891976/230631631-b77c2d7b-1cd0-414e-9371-a2c0e30a870a.png)
Аналогично для UserController и для сервисов.

2023-04-07 15:35 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (!filmsByID.get(filmId).getUsersLikes().contains(userId)) {
Рекомендация: На строке 124 и 130 происходит одно и то же действие, чтобы этого избежать можно фильм класть в переменную и уже работать с ней. Таким образом мы будем меньше нагружать наше хранилище
![image](https://user-images.githubusercontent.com/51891976/230634555-5be82a40-4501-40c6-add2-41310301c9f3.png)
Аналогично для метода makeUserLIke.

2023-04-07 15:35 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public void unlike(long filmId, long userId) {
Необходимо исправить: Все методы ниже будет лучше сделать с модификатором private, так как они относятся только к логике хранилища.

2023-04-07 15:35 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public void validateFilm(Film film) {
Рекомендация: Рекомендую вынести валидацию в сервис, так как хранилище отвечает только непосредственно за вставку/обновление/получение данных. Также можно оставить только проверку на дату релиза, так как все остальное проверяется с помощью аннотаций на входе в контроллер.

2023-04-07 15:35 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public void makeFriends(Long userId, Long friendId) {
Необходимо исправить: Все методы ниже будет лучше сделать с модификатором private, так как они относятся только к логике хранилища.

2023-04-07 15:35 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    public Film addUserLike(long filmId, long userId) {
Необходимо исправить: Для методов addUserLike и deleteLike отсутствует проверка на существование пользователя. Ее необходимо доабвить.

2023-04-07 15:35 UTC, ohelly commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> -package ru.yandex.practicum.filmorate.controller;
Необходимо исправить: А почему были удалены тесты? Они должны остаться, либо можно написать новые, для тестирования сервисов.

2023-04-08 20:46 UTC, kruglikovv commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService) {
Действительно! Добавил аннотацию @RequiredArgsConstructor в контролеры и сервисы. Спасибо;)

2023-04-08 20:51 UTC, kruglikovv commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (!filmsByID.get(filmId).getUsersLikes().contains(userId)) {
Понял. Готово!

2023-04-08 20:53 UTC, kruglikovv commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public void unlike(long filmId, long userId) {
Исправил. Спасибо! ;)

2023-04-08 20:55 UTC, kruglikovv commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public void makeFriends(Long userId, Long friendId) {
Исправил

2023-04-08 21:05 UTC, kruglikovv commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    private final UserStorage userStorage;
Удалил ссылку на UserStorage, это артефакт предыдущих версий реализации. Но за совет спасибо, принял к сведению! ;)

2023-04-08 21:18 UTC, kruglikovv commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public void validateFilm(Film film) {
Исправил. Спасибо за совет!

2023-04-08 21:42 UTC, kruglikovv commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public void validateUser(User user) {
Исправил. Проверку оставил, так как @Pattern (если я правильно нагуглил использование регулярноого выражения для исключения пробелов) не дает в 11й версии JDK и требует обновления до 15.
![Снимок экрана 2023-04-09 в 0 40 48](https://user-images.githubusercontent.com/117912035/230743692-452f240e-a04c-4a24-ac2a-aca809bff77d.png)

2023-04-08 21:49 UTC, kruglikovv commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    public Film addUserLike(long filmId, long userId) {
Да, это надо было сделать. Использовал метод `userService.getUserById(userId)`, который уже проверяет на наличие запрошенного юзера.

2023-04-08 21:53 UTC, kruglikovv commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> -package ru.yandex.practicum.filmorate.controller;
Тесты были удалены, потому что в ТЗ №10 такая задача не стоит, а в ТЗ №9 требовались только юнит-тесты и наш наставник подтвердил, что юнит-тесты не нужны (если валидация выполнена с помощью аннотаций). Так как в ТЗ №10 я реализовал твои рекомендации (по итогам ТЗ №9) и обещал (и перешел) на валидацию с помощью аннотаций, то поэтому блок тестов удалил.

2023-04-08 22:08 UTC, kruglikovv commented
Все замечания исправил. В postman все тесты прошел
![Снимок экрана 2023-04-09 в 1 07 15](https://user-images.githubusercontent.com/117912035/230744522-f4cb9184-01b5-447b-859c-09a432109430.png)

2023-04-09 12:04 UTC, ohelly approved these changes
Привет! Все супер, исправлены все замечания. Можно двигаться дальше, работу принимаю.

2023-04-10 06:51 UTC, merged